services:
  - type: web
    name: smart-finance-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_finance.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: ""
      - key: GEMINI_API_KEY
        value: ""
